# Generated by Django 5.1.4 on 2025-01-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweeterprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweeterprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
